# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.record_consumption import RecordConsumption  # noqa: F401,E501
from swagger_server import util


class ConsumptionResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: int=None, message: str=None, data: RecordConsumption=None):  # noqa: E501
        """ConsumptionResponse - a model defined in Swagger

        :param code: The code of this ConsumptionResponse.  # noqa: E501
        :type code: int
        :param message: The message of this ConsumptionResponse.  # noqa: E501
        :type message: str
        :param data: The data of this ConsumptionResponse.  # noqa: E501
        :type data: RecordConsumption
        """
        self.swagger_types = {
            'code': int,
            'message': str,
            'data': RecordConsumption
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message',
            'data': 'data'
        }
        self._code = code
        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'ConsumptionResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConsumptionResponse of this ConsumptionResponse.  # noqa: E501
        :rtype: ConsumptionResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this ConsumptionResponse.


        :return: The code of this ConsumptionResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this ConsumptionResponse.


        :param code: The code of this ConsumptionResponse.
        :type code: int
        """

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this ConsumptionResponse.


        :return: The message of this ConsumptionResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ConsumptionResponse.


        :param message: The message of this ConsumptionResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> RecordConsumption:
        """Gets the data of this ConsumptionResponse.


        :return: The data of this ConsumptionResponse.
        :rtype: RecordConsumption
        """
        return self._data

    @data.setter
    def data(self, data: RecordConsumption):
        """Sets the data of this ConsumptionResponse.


        :param data: The data of this ConsumptionResponse.
        :type data: RecordConsumption
        """

        self._data = data
