# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DepositBalanceRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, client_id: int=None, balance: int=None):  # noqa: E501
        """DepositBalanceRequest - a model defined in Swagger

        :param client_id: The client_id of this DepositBalanceRequest.  # noqa: E501
        :type client_id: int
        :param balance: The balance of this DepositBalanceRequest.  # noqa: E501
        :type balance: int
        """
        self.swagger_types = {
            'client_id': int,
            'balance': int
        }

        self.attribute_map = {
            'client_id': 'client_id',
            'balance': 'balance'
        }
        self._client_id = client_id
        self._balance = balance

    @classmethod
    def from_dict(cls, dikt) -> 'DepositBalanceRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DepositBalanceRequest of this DepositBalanceRequest.  # noqa: E501
        :rtype: DepositBalanceRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def client_id(self) -> int:
        """Gets the client_id of this DepositBalanceRequest.


        :return: The client_id of this DepositBalanceRequest.
        :rtype: int
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id: int):
        """Sets the client_id of this DepositBalanceRequest.


        :param client_id: The client_id of this DepositBalanceRequest.
        :type client_id: int
        """
        if client_id is None:
            raise ValueError("Invalid value for `client_id`, must not be `None`")  # noqa: E501

        self._client_id = client_id

    @property
    def balance(self) -> int:
        """Gets the balance of this DepositBalanceRequest.


        :return: The balance of this DepositBalanceRequest.
        :rtype: int
        """
        return self._balance

    @balance.setter
    def balance(self, balance: int):
        """Sets the balance of this DepositBalanceRequest.


        :param balance: The balance of this DepositBalanceRequest.
        :type balance: int
        """
        if balance is None:
            raise ValueError("Invalid value for `balance`, must not be `None`")  # noqa: E501

        self._balance = balance
