# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.login_response_data import LoginResponseData  # noqa: F401,E501
from swagger_server import util


class LoginResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: int=None, message: str=None, data: LoginResponseData=None):  # noqa: E501
        """LoginResponse - a model defined in Swagger

        :param code: The code of this LoginResponse.  # noqa: E501
        :type code: int
        :param message: The message of this LoginResponse.  # noqa: E501
        :type message: str
        :param data: The data of this LoginResponse.  # noqa: E501
        :type data: LoginResponseData
        """
        self.swagger_types = {
            'code': int,
            'message': str,
            'data': LoginResponseData
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message',
            'data': 'data'
        }
        self._code = code
        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'LoginResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginResponse of this LoginResponse.  # noqa: E501
        :rtype: LoginResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this LoginResponse.


        :return: The code of this LoginResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this LoginResponse.


        :param code: The code of this LoginResponse.
        :type code: int
        """

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this LoginResponse.


        :return: The message of this LoginResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this LoginResponse.


        :param message: The message of this LoginResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> LoginResponseData:
        """Gets the data of this LoginResponse.


        :return: The data of this LoginResponse.
        :rtype: LoginResponseData
        """
        return self._data

    @data.setter
    def data(self, data: LoginResponseData):
        """Sets the data of this LoginResponse.


        :param data: The data of this LoginResponse.
        :type data: LoginResponseData
        """

        self._data = data
