# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RecordConsumption(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, client_id: int=None, balance: int=None, consumption: int=None, minutes: int=None):  # noqa: E501
        """RecordConsumption - a model defined in Swagger

        :param client_id: The client_id of this RecordConsumption.  # noqa: E501
        :type client_id: int
        :param balance: The balance of this RecordConsumption.  # noqa: E501
        :type balance: int
        :param consumption: The consumption of this RecordConsumption.  # noqa: E501
        :type consumption: int
        :param minutes: The minutes of this RecordConsumption.  # noqa: E501
        :type minutes: int
        """
        self.swagger_types = {
            'client_id': int,
            'balance': int,
            'consumption': int,
            'minutes': int
        }

        self.attribute_map = {
            'client_id': 'client_id',
            'balance': 'balance',
            'consumption': 'consumption',
            'minutes': 'minutes'
        }
        self._client_id = client_id
        self._balance = balance
        self._consumption = consumption
        self._minutes = minutes

    @classmethod
    def from_dict(cls, dikt) -> 'RecordConsumption':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RecordConsumption of this RecordConsumption.  # noqa: E501
        :rtype: RecordConsumption
        """
        return util.deserialize_model(dikt, cls)

    @property
    def client_id(self) -> int:
        """Gets the client_id of this RecordConsumption.


        :return: The client_id of this RecordConsumption.
        :rtype: int
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id: int):
        """Sets the client_id of this RecordConsumption.


        :param client_id: The client_id of this RecordConsumption.
        :type client_id: int
        """
        if client_id is None:
            raise ValueError("Invalid value for `client_id`, must not be `None`")  # noqa: E501

        self._client_id = client_id

    @property
    def balance(self) -> int:
        """Gets the balance of this RecordConsumption.


        :return: The balance of this RecordConsumption.
        :rtype: int
        """
        return self._balance

    @balance.setter
    def balance(self, balance: int):
        """Sets the balance of this RecordConsumption.


        :param balance: The balance of this RecordConsumption.
        :type balance: int
        """
        if balance is None:
            raise ValueError("Invalid value for `balance`, must not be `None`")  # noqa: E501

        self._balance = balance

    @property
    def consumption(self) -> int:
        """Gets the consumption of this RecordConsumption.


        :return: The consumption of this RecordConsumption.
        :rtype: int
        """
        return self._consumption

    @consumption.setter
    def consumption(self, consumption: int):
        """Sets the consumption of this RecordConsumption.


        :param consumption: The consumption of this RecordConsumption.
        :type consumption: int
        """
        if consumption is None:
            raise ValueError("Invalid value for `consumption`, must not be `None`")  # noqa: E501

        self._consumption = consumption

    @property
    def minutes(self) -> int:
        """Gets the minutes of this RecordConsumption.


        :return: The minutes of this RecordConsumption.
        :rtype: int
        """
        return self._minutes

    @minutes.setter
    def minutes(self, minutes: int):
        """Sets the minutes of this RecordConsumption.


        :param minutes: The minutes of this RecordConsumption.
        :type minutes: int
        """
        if minutes is None:
            raise ValueError("Invalid value for `minutes`, must not be `None`")  # noqa: E501

        self._minutes = minutes
