# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TransactionsResponseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, balance: int=None, creation_date: str=None, type: int=None):  # noqa: E501
        """TransactionsResponseData - a model defined in Swagger

        :param balance: The balance of this TransactionsResponseData.  # noqa: E501
        :type balance: int
        :param creation_date: The creation_date of this TransactionsResponseData.  # noqa: E501
        :type creation_date: str
        :param type: The type of this TransactionsResponseData.  # noqa: E501
        :type type: int
        """
        self.swagger_types = {
            'balance': int,
            'creation_date': str,
            'type': int
        }

        self.attribute_map = {
            'balance': 'balance',
            'creation_date': 'creation_date',
            'type': 'type'
        }
        self._balance = balance
        self._creation_date = creation_date
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'TransactionsResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TransactionsResponseData of this TransactionsResponseData.  # noqa: E501
        :rtype: TransactionsResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def balance(self) -> int:
        """Gets the balance of this TransactionsResponseData.


        :return: The balance of this TransactionsResponseData.
        :rtype: int
        """
        return self._balance

    @balance.setter
    def balance(self, balance: int):
        """Sets the balance of this TransactionsResponseData.


        :param balance: The balance of this TransactionsResponseData.
        :type balance: int
        """

        self._balance = balance

    @property
    def creation_date(self) -> str:
        """Gets the creation_date of this TransactionsResponseData.


        :return: The creation_date of this TransactionsResponseData.
        :rtype: str
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date: str):
        """Sets the creation_date of this TransactionsResponseData.


        :param creation_date: The creation_date of this TransactionsResponseData.
        :type creation_date: str
        """

        self._creation_date = creation_date

    @property
    def type(self) -> int:
        """Gets the type of this TransactionsResponseData.


        :return: The type of this TransactionsResponseData.
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type: int):
        """Sets the type of this TransactionsResponseData.


        :param type: The type of this TransactionsResponseData.
        :type type: int
        """

        self._type = type
